---
- name: Download Docker logs from consensus-node and seismic-reth
  hosts: ec2_instances
  become: true
  vars:
    local_base_dir: "./docker_logs"

  tasks:

    ##########################################
    # Logs from consensus-node
    ##########################################
    - name: Get full container ID for consensus-node
      ansible.builtin.shell: >
        docker inspect --format='{{ "{{.Id}}" }}' $(docker ps -qf name=consensus-node)
      register: consensus_id_raw
      changed_when: false

    - name: Ensure container ID was found for consensus-node
      ansible.builtin.fail:
        msg: "No container found with name 'consensus-node'"
      when: consensus_id_raw.stdout | trim == ""

    - name: Set fact for consensus container ID
      ansible.builtin.set_fact:
        consensus_container_id: "{{ consensus_id_raw.stdout | trim }}"

    - name: Ensure local log directory exists for consensus-node
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: "{{ local_base_dir }}/{{ inventory_hostname }}/consensus-node"
        state: directory
        mode: '0755'

    - name: Find all Docker log files for consensus-node
      ansible.builtin.find:
        paths: "/var/lib/docker/containers/{{ consensus_container_id }}"
        patterns: "*.log*"
      register: consensus_logs

    - name: Fetch Docker log files for consensus-node
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ local_base_dir }}/{{ inventory_hostname }}/consensus-node/"
        flat: yes
      with_items: "{{ consensus_logs.files }}"

    ##########################################
    # Logs from seismic-reth
    ##########################################
    - name: Get full container ID for seismic-reth
      ansible.builtin.shell: >
        docker inspect --format='{{ "{{.Id}}" }}' $(docker ps -qf name=seismic-reth)
      register: reth_id_raw
      changed_when: false

    - name: Ensure container ID was found for seismic-reth
      ansible.builtin.fail:
        msg: "No container found with name 'seismic-reth'"
      when: reth_id_raw.stdout | trim == ""

    - name: Set fact for seismic-reth container ID
      ansible.builtin.set_fact:
        reth_container_id: "{{ reth_id_raw.stdout | trim }}"

    - name: Ensure local log directory exists for seismic-reth
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: "{{ local_base_dir }}/{{ inventory_hostname }}/seismic-reth"
        state: directory
        mode: '0755'

    - name: Find all Docker log files for seismic-reth
      ansible.builtin.find:
        paths: "/var/lib/docker/containers/{{ reth_container_id }}"
        patterns: "*.log*"
      register: reth_logs

    - name: Fetch Docker log files for seismic-reth
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ local_base_dir }}/{{ inventory_hostname }}/seismic-reth/"
        flat: yes
      with_items: "{{ reth_logs.files }}"

